name: Ubuntu SSH Access and aapanel Setup
on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Set up SSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server wget jq
        sudo systemctl enable ssh
        sudo systemctl start ssh
        # Set a password for the default user 'runner'
        echo "runner:P@ssw0rd" | sudo chpasswd

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar xf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ./ngrok

    - name: Authenticate ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Expose SSH via ngrok
      run: |
        ./ngrok tcp 22 > /dev/null &
        sleep 5
        curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    - name: Install aapanel
      run: |
        wget -O install.sh http://www.aapanel.com/script/install-ubuntu_6.0_en.sh
        sudo bash install.sh
        aapanel_info=$(cat /root/.lamplog/install.log | grep "The panel URL is" -A 2)
        echo "$aapanel_info"

    - name: Install Playit
      run: |
        wget https://github.com/thatcoder/playit-agent/releases/download/v0.3.0/playit-linux_x86_64.tar.gz
        tar -xvf playit-linux_x86_64.tar.gz
        chmod +x ./playit
        playit_output=$(./playit login)
        echo "$playit_output"

    - name: Keep the job running
      run: sleep 1d
