
name: Windows RDP Access
on: [push, workflow_dispatch]

jobs:
  setup-rdp:
    runs-on: windows-latest
    steps:
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install 7zip, Notepad++, e JoyToKey
        run: |
          choco install 7zip notepadplusplus joytokey -y

      - name: Install Lightweight Game (SuperTuxKart)
        run: |
          choco install supertuxkart -y

      - name: Download and Install Ngrok
        run: |
          Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath $Env:UserProfile
          $env:Path += ";$Env:UserProfile"

      - name: Configure Ngrok
        run: |
          .\ngrok.exe authtoken $env:NGROK_AUTH_TOKEN

      - name: Start RDP Service
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Start Ngrok Tunnel for RDP
        run: |
          Start-Process -FilePath .\ngrok.exe -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 10
          $ngrok_url = (Invoke-WebRequest -UseBasicParsing -Uri http://127.0.0.1:4040/api/tunnels/command_line).Content | ConvertFrom-Json | Select-Object -ExpandProperty public_url
          Write-Host "Use the following address to connect via RDP:"
          Write-Host $ngrok_url
          Write-Host "Username: runneradmin"
          Write-Host "Password: $env:ADMIN_PASSWORD"

      - name: Keep the job running
        run: |
          Start-Sleep -Seconds 10800  # Keeps the session active for 3 hours
        timeout-minutes: 180
    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
