name: Ubuntu SSH Access

on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh
        echo "runner:P@ssw0rd" | sudo chpasswd # Define a senha 'P@ssw0rd' para o usuário 'runner'

    - name: Install LocalXpose
      uses: localxpose/cli@v1.6.0
      with:
        # Configure LocalXpose to expose port 22 (SSH)
        services: '22:ssh'

    - name: Get SSH Connection Information
      id: get-ssh-info
      uses: localxpose/cli@v1.6.0
      with:
        command: info

    - name: Print SSH Connection Command
      run: |
        echo "Connecting to SSH server..."
        echo "ssh runner@${{ steps.get-ssh-info.outputs.host }} -p ${{ steps.get-ssh-info.outputs.port }}"

    # Keep the workflow running to maintain the connection
    - name: Keep Job Alive
      run: sleep 1d 
