name: Ubuntu Desktop Access

on: [push, workflow_dispatch]

jobs:
  setup-remote-desktop:
    runs-on: ubuntu-latest

    steps:
    - name: Set up MATE Desktop Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y ubuntu-mate-desktop xrdp wget jq
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        # Set a password for the default user 'runner'
        echo "runner:P@ssw0rd" | sudo chpasswd
        # Configure xrdp to use the MATE session
        echo "mate-session" > ~/.xsession

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar xf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ./ngrok

    - name: Authenticate ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Expose XRDP via ngrok
      run: |
        ./ngrok tcp 3389 > /dev/null &
        sleep 5
        curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    - name: Keep the job running
      run: sleep 1d
