name: Ubuntu SSH Access

on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server npm
        sudo npm install -g localtunnel
        sudo systemctl enable ssh
        sudo systemctl start ssh
        # Set a password for the default user 'runner'
        echo "runner:P@ssw0rd" | sudo chpasswd
        # Reinicia o serviço SSH
        sudo systemctl restart ssh

    - name: Expose SSH via LocalTunnel
      id: expose
      run: |
        # Estabelece o túnel via LocalTunnel e captura a URL
        SERVEO_URL=$(lt -p 22 --print-requests | grep -o 'https://.*\.loca.lt' | tail -n1 &)
        sleep 5
        
        # Verifica se a URL foi capturada
        if [ -z "$SERVEO_URL" ]; then
          echo "Failed to retrieve LocalTunnel URL."
          exit 1
        fi
        
        echo "Use this command to connect via SSH:"
        echo "ssh runner@$SERVEO_URL"

    - name: Keep the job running
      run: sleep 1d
