name: Ubuntu SSH Access

on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server wget jq dnsutils
        sudo systemctl enable ssh
        sudo systemctl start ssh
        # Set a password for the default user 'runner'
        echo "runner:P@ssw0rd" | sudo chpasswd

    - name: Install LocalXpose
      run: |
        wget https://loclx-client.s3.amazonaws.com/loclx-linux-amd64.zip
        unzip loclx-linux-amd64.zip
        chmod +x loclx
        sudo mv loclx /usr/local/bin/

    - name: Verify LocalXpose installation
      run: |
        which loclx
        loclx version  # Verifica a versão para garantir que está instalado corretamente

    - name: Authenticate LocalXpose
      run: |
        /usr/local/bin/loclx authtoken ${{ secrets.LOCALXPOSE_AUTH_TOKEN }} --headless

    - name: Expose SSH via LocalXpose
      run: |
        /usr/local/bin/loclx tcp 22 --headless > /dev/null &
        sleep 5
        LOCALXPOSE_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        LOCALXPOSE_DOMAIN=$(echo $LOCALXPOSE_URL | cut -d':' -f1 | cut -d'/' -f3)
        LOCALXPOSE_PORT=$(echo $LOCALXPOSE_URL | cut -d':' -f2)
        echo "Use this command to connect via SSH:"
        echo "ssh runner@$LOCALXPOSE_DOMAIN -p $LOCALXPOSE_PORT"

    - name: Keep the job running
      run: sleep 1d
