name: Ubuntu SSH Access

on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server wget jq dnsutils
        sudo systemctl enable ssh
        sudo systemctl start ssh
        # Set a password for the default user 'runner'
        echo "runner:P@ssw0rd" | sudo chpasswd

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar xf ngrok-stable-v3-linux-amd64.tgz
        chmod +x ./ngrok

    - name: Authenticate ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Expose SSH via ngrok and resolve to IP
      run: |
        ./ngrok tcp 22 > /dev/null &
        sleep 5
        NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        NGROK_DOMAIN=$(echo $NGROK_URL | cut -d':' -f1 | cut -d'/' -f3)
        NGROK_PORT=$(echo $NGROK_URL | cut -d':' -f2)
        NGROK_IP=$(dig +short $NGROK_DOMAIN | tail -n1)
        echo "Use this command to connect via SSH:"
        echo "ssh runner@$NGROK_IP -p $NGROK_PORT"

    - name: Keep the job running
      run: sleep 1d
