name: Ubuntu SSH Access

on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server wget jq dnsutils
        sudo systemctl enable ssh
        sudo systemctl start ssh
        # Set a password for the default user 'runner'
        echo "runner:P@ssw0rd" | sudo chpasswd

    - name: Expose SSH via Serveo and resolve to IP
      run: |
        # Estabelece o túnel via Serveo
        ssh -tt -o StrictHostKeyChecking=no -R 80:localhost:22 serveo.net > /dev/null &
        sleep 5
        # Resolve a URL do túnel e extrai o domínio e porta
        SERVEO_DOMAIN="serveo.net"
        SERVEO_IP=$(dig +short $SERVEO_DOMAIN | tail -n1)
        echo "Use this command to connect via SSH:"
        echo "ssh runner@$SERVEO_IP -p 22"  # Serveo utiliza a porta 22 para conexões SSH

    - name: Keep the job running
      run: sleep 1d
