name: Ubuntu SSH Access

on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server wget jq
        sudo systemctl enable ssh
        sudo systemctl start ssh
        echo "runner:P@ssw0rd" | sudo chpasswd

    - name: Install ZeroTier
      run: |
        curl -s https://install.zerotier.com | sudo bash
        sudo zerotier-cli join ${{ secrets.ZEROTIER_NETWORK_ID }}

    - name: Get ZeroTier IP
      run: |
        sleep 10
        zerotier-cli listpeers
        ip=$(ip -4 -o addr show dev zt0 | awk '{split($4,a,"/");print a[1]}')
        echo "ZeroTier IP: $ip"

    - name: Keep the job running
      run: sleep 1d
