name: Ubuntu SSH Access

on: [push, workflow_dispatch]

jobs:
  setup-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server wget jq dnsutils
        sudo systemctl enable ssh
        sudo systemctl start ssh
        # Set a password for the default user 'runner'
        echo "runner:P@ssw0rd" | sudo chpasswd
        # Reinicia o serviço SSH
        sudo systemctl restart ssh

    - name: Expose SSH via Serveo and capture the URL
      run: |
        # Estabelece o túnel via Serveo e captura a saída
        ssh -o StrictHostKeyChecking=no -R 80:localhost:22 serveo.net -N > serveo_output.txt 2>&1 &
        sleep 5
        
        # Lê a URL gerada a partir da saída
        SERVEO_URL=$(grep -o 'https://.*\.serveo\.net' serveo_output.txt | tail -n1)
        
        # Verifica se a URL foi capturada
        if [ -z "$SERVEO_URL" ]; then
          echo "Failed to retrieve Serveo URL."
          exit 1
        fi
        
        echo "Use this command to connect via SSH:"
        echo "ssh runner@$SERVEO_URL"

    - name: Keep the job running
      run: sleep 1d
